Harika! Artık makine öğrenmesinin **yapılandırılmamış veriden örüntü çıkaran**, çok özel ve güçlü bir alanına geçtin:

## 🧠 **Association Rule Learning (Bağlantı/Kurallar Öğrenme)**

Bu bölümde, özellikle **pazarlama, satış analizi, öneri sistemleri** gibi alanlarda sıkça kullanılan **kural tabanlı öğrenme** modelleri öğreneceksin.

İlk konun: **Apriori Algoritması** olacak. Sana hem bu bölümün genel yapısını hem de Apriori'yi sade şekilde anlatayım:

---

# 📌 Association Rule Learning Nedir?

Association Rule Learning, **veri içerisindeki öğeler (özellikler, ürünler, olaylar) arasındaki ilişkileri/kombinasyonları** bulmak için kullanılır.

### En bilinen örnek:

> "Market sepeti analizi" (Market Basket Analysis)

> ❓“Müşteri ekmek aldıysa, yanında genellikle ne alıyor?”
> ❓“Bir ürünü alan müşteriler genellikle hangi ürünleri de alır?”

Yani:

* **Eş zamanlı görülen öğeler**
* **Birlikte satın alınan ürünler**
* **Sebep–sonuç olabilecek kural desenleri**

---

## 🧾 Kurallar Şu Formatta Olur:

```
A ⇒ B
```

> "Eğer A varsa, B olma olasılığı yüksektir"

Örnek:

```
{Ekmek, Süt} ⇒ {Yumurta}
```

---

## 📊 Kullanılan Metrikler:

| Metrik         | Açıklama                                                                                    |
| -------------- | ------------------------------------------------------------------------------------------- |
| **Support**    | A ve B’nin birlikte görülme oranı (destek)                                                  |
| **Confidence** | A olduktan sonra B’nin de görülme olasılığı (güven)                                         |
| **Lift**       | A ve B'nin birlikte görülmesi, B'nin bağımsız görülmesine göre ne kadar güçlü? (anlamlılık) |

---

## 📌 Apriori Algoritması Nedir?

**Apriori**, Association Rule Learning’de en çok bilinen algoritmadır.

> Amaç: “En sık birlikte görülen öğe kümelerini bul, sonra bu kümelerden anlamlı kurallar türet.”

---

### 🔁 Nasıl Çalışır?

1. **Destek değeri eşik (min support)** belirlenir
2. Bu eşiği geçen öğeler (tekli, ikili, üçlü vb.) bulunur
3. Bu sık öğe kümelerinden **A ⇒ B** şeklinde kurallar üretilir
4. Kuralların **confidence** ve **lift** değerleri hesaplanır
5. Anlamlı olanlar filtrelenir

---

### 🎯 Neden "Apriori"?

Çünkü algoritma "Apriori özelliği"ni kullanır:

> "Eğer bir öğe grubu nadirse, onun alt kümeleri de nadirdir"
> Bu sayede **gereksiz kombinasyonlar elenir**, işlem hızlanır

---

## ✅ Avantajları:

| Özellik                   | Açıklama                                               |
| ------------------------- | ------------------------------------------------------ |
| Yorumlaması kolay         | “Eğer bu varsa, bu da olur” tarzı net kurallar üretir  |
| Öneri sistemlerinde güçlü | Ürün, içerik, kullanıcı alışkanlıkları için kullanılır |
| Sıklık tabanlı            | Güçlü korelasyonları kolay yakalar                     |

---

## ⚠️ Dezavantajları:

| Sınırlama                            | Açıklama                                             |
| ------------------------------------ | ---------------------------------------------------- |
| Büyük veriyle yavaş                  | Kombinasyonlar çok fazla olabilir                    |
| Min support/confidence seçimi önemli | Yanlış eşikler ya çok az ya da alakasız kural üretir |
| Sadece varlık yokluk bakar           | Nicel değerleri (örneğin miktar) direkt işlemez      |

---

## 💻 Python'da Apriori Örneği (mlxtend kütüphanesi ile):

```python
from mlxtend.frequent_patterns import apriori, association_rules

# 1. Sık öğe kümelerini bul
frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True)

# 2. Kuralları üret
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)

# 3. Güçlü kuralları filtrele
strong_rules = rules[(rules['confidence'] > 0.6) & (rules['lift'] > 1.2)]
```

---

## 📦 Tipik Kullanım Alanları:

* 🛒 Market sepet analizi
* 📧 E-posta kampanyası optimizasyonu
* 📺 İzleyici alışkanlıkları
* 🛍️ Online mağaza öneri sistemleri
* 🕵️‍♂️ Dolandırıcılık tespiti

---

## 🎓 Özetle:

| Başlık                  | İçerik                                   |
| ----------------------- | ---------------------------------------- |
| Konu                    | Denetimsiz öğrenme, ilişki keşfi         |
| Model türü              | Kural tabanlı (A ⇒ B)                    |
| Apriori algoritması     | En sık öğe kümelerini bul, kurallar üret |
| Metrikler               | Support, Confidence, Lift                |
| En çok kullanıldığı yer | Market sepeti analizi, öneri sistemleri  |

---

Videoyu izledikten sonra birlikte gerçek bir alışveriş verisinde `Apriori` kullanabilir, `lift > 1` olan güçlü önerileri yorumlayabiliriz.

Sonraki konun muhtemelen **ECLAT algoritması** olacak — o da çok kısa ama pratik bir alternatiftir. Hazır olduğunda ona da geçebiliriz!

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Market_Basket_Optimisation.csv', header = None) # headeri yok
transactions = []
for i in range(0, 7501):
  transactions.append([str(dataset.values[i,j]) for j in range(0, 20)])

## Training the Apriori model on the dataset

In [8]:
from apyori import apriori
rules = apriori(
            transactions = transactions, 
            min_support = 0.003, # en az 3 ürün alımı.  * en. çok ürün alımı  / veri satır. sayısı
            min_confidence = 0.2,   # rastgele. veriye göre denenerek seçilir
            min_lift = 3, # 3 olsun dedi
            min_length = 2, 
            max_length = 2) #şimdi bir ürün alana 2. bedava vereceğimiz için 2 yaptı min max ı

Bu çok önemli bir soru ve **Apriori algoritmasında başarıyı belirleyen en kritik yer tam olarak burası**:
Yani `min_support`, `min_confidence`, `min_lift`, `min_length`, `max_length` gibi **eşik (threshold)** değerlerinin **neden seçildiği ve nasıl değiştiği** konusu.

Şimdi sana bu parametrelerin **ne işe yaradığını**, **neden böyle verildiğini** ve **nasıl ayarlanması gerektiğini** açıklayayım:

---

## 🔍 Kod Parçası:

```python
rules = apriori(
    transactions = transactions, 
    min_support = 0.003,
    min_confidence = 0.2,  
    min_lift = 3, 
    min_length = 2, 
    max_length = 2)
```

---

## 1️⃣ `min_support = 0.003`

### 📌 Ne demek?

* En az %0.3 destek oranına sahip öğe kombinasyonlarını dikkate al.

### 🎯 Neden böyle?

* Diyelim veri setinde 10.000 işlem var.
* 0.003 destek = **en az 30 işlemde görülen kombinasyonlar**
* Çok nadir görülen kombinasyonlar göz ardı edilir

### 🧠 Not:

* Büyük veri setinde küçük değer mantıklıdır
* Küçük veri setinde daha yüksek destek gerekir (`0.05`–`0.1` gibi)

---

## 2️⃣ `min_confidence = 0.2`

### 📌 Ne demek?

* A ⇒ B kuralının en az %20 güvenilirliği (doğruluğu) olmalı

### 🎯 Neden böyle?

* `P(B | A)` ≥ 0.2 olmalı → A varsa B’nin de gelme olasılığı %20’nin altında olmasın

### 🧠 Not:

* Düşük confidence: zayıf ilişki
* Yüksek confidence: daha anlamlı ama az sayıda kural çıkarır
* Genelde `0.5`–`0.8` arası seçilir
* Ama burada **daha çok kural çıkarılsın diye 0.2 verilmiş**

---

## 3️⃣ `min_lift = 3`

### 📌 Ne demek?

* Lift ≥ 3 olacak → A ve B birlikte olması, B’nin bağımsız oluşundan **en az 3 kat daha olası**

### 🎯 Neden böyle?

* Lift = 1 → rastgele ilişki
* Lift > 1 → olumlu ilişki
* Lift ≥ 3 → **kuvvetli ilişki** demektir (süpermarket verisinde sık kullanılır)

### 🧠 Not:

* `lift > 1.2` → anlamlı
* `lift > 2` → güçlü
* `lift > 3` → çok güçlü
* Bu eşik, çıkarılan kuralların **gerçekten güvenilir** olmasını sağlar

---

## 4️⃣ `min_length = 2`, `max_length = 2`

### 📌 Ne demek?

* Kurallar sadece **2 öğe** içersin (`A ⇒ B` gibi)

### 🎯 Neden böyle?

* Basit, okunabilir ve pratik kurallar istenmiş
* Örnek: `{süt} ⇒ {ekmek}`

### 🧠 Not:

* Eğer `min_length=2`, `max_length=3` dersen
  → 2’li ve 3’lü kuralları da alırsın: `{süt, tereyağı} ⇒ {ekmek}` gibi
* Daha büyük kombinasyonlar = daha karmaşık ama bazen daha ilginç sonuçlar

---

## 🧠 Sonuç: Bu Eşikler “Sabit” Değil

Bunlar:

✅ Veri büyüklüğüne
✅ İşin doğasına (market verisi mi, tıklama mı, sağlık mı)
✅ Beklenen sonuçların yoğunluğuna göre
**değiştirilebilir**

---

## 📊 Örnek Alternatif Değer Setleri:

| Kullanım Amacı             | min\_support | min\_confidence | min\_lift | Açıklama                                    |
| -------------------------- | ------------ | --------------- | --------- | ------------------------------------------- |
| Market verisi (büyük veri) | 0.002–0.005  | 0.2–0.5         | 2–3       | Çok işlem var, sık gelen kombinasyon aranır |
| Küçük veri seti            | 0.05–0.1     | 0.5–0.8         | 1.2+      | Az veri olduğunda eşikler yükseltilir       |
| Yoğun öneri çıkarma        | 0.001        | 0.1             | 1         | Daha fazla ama zayıf kural çıkarılır        |

---

## 🎓 Özetle:

| Parametre        | Ne İşe Yarar?                            |
| ---------------- | ---------------------------------------- |
| `min_support`    | En az kaç kez görünmeli? (frekans eşiği) |
| `min_confidence` | Kuralın güvenilirliği ne kadar olmalı?   |
| `min_lift`       | Rastgeleliğe göre ne kadar güçlü ilişki? |
| `min_length`     | En kısa kaç öğeli kural?                 |
| `max_length`     | En uzun kaç öğeli kural?                 |

---

İstersen aynı veride bu eşiklerle oynayıp kaç kural çıktığını, nasıl değiştiğini birlikte test edebiliriz.
Sonraki videon **ECLAT** olacak — daha sade ama destek tabanlı bir yöntem. Hazırsan ona da seni hazırlarım!

## Visualising the results

### Displaying the first results coming directly from the output of the apriori function

In [9]:
results = list(rules)

In [10]:
results

[RelationRecord(items=frozenset({'chicken', 'light cream'}), support=0.004532728969470737, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)]),
 RelationRecord(items=frozenset({'escalope', 'mushroom cream sauce'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]),
 RelationRecord(items=frozenset({'escalope', 'pasta'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)]),
 RelationRecord(items=frozenset({'fromage blanc', 'honey'}), support=0.003332888948140248, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.164270764485569)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]),
 RelationRecord(items=frozenset({'tomato sauce', 'ground beef'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3773584905660377, lift=3.840659481324083)]),
 RelationRecord(items=frozenset({'olive oil', 'light cream'}), support=0.003199573390214638, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820515, lift=3.1147098515519573)]),
 RelationRecord(items=frozenset({'olive oil', 'whole wheat pasta'}), support=0.007998933475536596, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.122410097642296)]),
 RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050847, lift=4.506672147735896)])]

misal ilk kuralda krem alan tavuk alır diyor, %29 alma olasılığı varmı confidence göre, support ile yüzde 45 oranda insanlar böyle yapmış diyor

### Putting the results well organised into a Pandas DataFrame

In [11]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

### Displaying the results non sorted

In [12]:
resultsinDataFrame

         Left Hand Side Right Hand Side   Support  Confidence      Lift
0           light cream         chicken  0.004533    0.290598  4.843951
1  mushroom cream sauce        escalope  0.005733    0.300699  3.790833
2                 pasta        escalope  0.005866    0.372881  4.700812
3         fromage blanc           honey  0.003333    0.245098  5.164271
4         herb & pepper     ground beef  0.015998    0.323450  3.291994
5          tomato sauce     ground beef  0.005333    0.377358  3.840659
6           light cream       olive oil  0.003200    0.205128  3.114710
7     whole wheat pasta       olive oil  0.007999    0.271493  4.122410
8                 pasta          shrimp  0.005066    0.322034  4.506672

### Displaying the results sorted by descending lifts

In [13]:
resultsinDataFrame.nlargest(n = 10, columns = 'Lift')

         Left Hand Side Right Hand Side   Support  Confidence      Lift
3         fromage blanc           honey  0.003333    0.245098  5.164271
0           light cream         chicken  0.004533    0.290598  4.843951
2                 pasta        escalope  0.005866    0.372881  4.700812
8                 pasta          shrimp  0.005066    0.322034  4.506672
7     whole wheat pasta       olive oil  0.007999    0.271493  4.122410
5          tomato sauce     ground beef  0.005333    0.377358  3.840659
1  mushroom cream sauce        escalope  0.005733    0.300699  3.790833
4         herb & pepper     ground beef  0.015998    0.323450  3.291994
6           light cream       olive oil  0.003200    0.205128  3.114710